template: "mockery"
tags: "custom2"
formatter: "goimports"
all: True
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "mocks_test.go"
boilerplate-file: "./.boilerplate.txt"
packages:
  github.com/vektra/mockery/v3/internal/fixtures/buildtag/comment:
  github.com/vektra/mockery/v3/internal/fixtures:
    interfaces:
      RequesterVariadic:
        configs:
          - mockname: MockRequesterVariadicOneArgument
            template-data:
              unroll-variadic: False
          - mockname: MockRequesterVariadic
            template-data:
              unroll-variadic: True
      Expecter:
        configs:
          - mockname: MockExpecterAndRolledVariadic
            template-data:
              unroll-variadic: False
          - mockname: MockExpecter
            template-data:
              unroll-variadic: True
      VariadicNoReturnInterface:
        config:
          template-data:
            unroll-variadic: False
  github.com/vektra/mockery/v3/internal/fixtures/recursive_generation:
    config:
      recursive: True
  github.com/vektra/mockery/v3/internal/fixtures/empty_return:
  github.com/vektra/mockery/v3/internal/fixtures/method_args/same_name_arg_and_type:
  github.com/vektra/mockery/v3/internal/fixtures/iface_typed_param:
  github.com/vektra/mockery/v3/internal/fixtures/example_project:
  github.com/vektra/mockery/v3/internal/fixtures/index_list_expr:
  github.com/vektra/mockery/v3/internal/fixtures/iface_new_type:
  github.com/vektra/mockery/v3/internal/fixtures/type_alias:

