template: moq
packages:
    github.com/vektra/mockery/v3/pkg/fixtures:
        config:
            dir: "{{.InterfaceDir}}"
            filename: "mocks_moq.go"
            pkgname: "test"
            mockname: "Moq{{.InterfaceName}}"
        interfaces:
            Requester: